# Makefile especializado para los testbenches de análisis léxico y sintáctico
CC = gcc
CFLAGS = -Wall -Wextra -g

SRC_DIR = .
# El Lexer solo necesita su código
SRC_LEXER = $(SRC_DIR)/lexer/lexer.c
# El Parser necesita el lexer y todos los módulos sintácticos
SRC_PARSER = $(SRC_DIR)/lexer/lexer.c \
             $(SRC_DIR)/parser/parser.c \

all: test_lexer test_parser

test_lexer: $(SRC_DIR)/tests/test_lexer.c $(SRC_LEXER)
	$(CC) $(CFLAGS) $^ -o $(SRC_DIR)/test_lexer_exec

test_parser: $(SRC_DIR)/tests/test_parser.c $(SRC_PARSER)
	$(CC) $(CFLAGS) $^ -o $(SRC_DIR)/test_parser_exec

clean:
	rm -f $(SRC_DIR)/test_lexer_exec $(SRC_DIR)/test_parser_exec